@startuml

title "山海经-第一层"

skinparam packageStyle rectangle

(中山经)-up->(北山经)
(中山经)-right->(东山经)
(中山经)-down->(南山经)
(中山经)-left->(西山经)

(南山经)-down->(海外南经)
(海外南经)-down->(海内南经)
(海内南经)-down->(大荒南经)

(西山经)-left->(海外西经)
(海外西经)-left->(海内西经)
(海内西经)-left->(大荒西经)

(北山经)-up->(海外北经)
(海外北经)-up->(海内北经)
(海内北经)-up->(大荒北经)

(东山经)-right->(海外东经)
(海外东经)-right->(海内东经)
(海内东经)-right->(大荒东经)

footer 版本：0.1，日期：2024/10/18

@enduml