@startuml

title "山海经-第三层"

skinparam packageStyle rectangle

rectangle 南山山系 {

    (南山之首-鹊山-招摇山)-right->(堂庭山):东三百里
    (堂庭山)-right->(猨翼山):东三百八十里
    (猨翼山)-right->(杻阳山):东三百七十里
    (杻阳山)-right->(柢山):东三百里
    (柢山)-right->(亶爰山):东四百里
    (亶爰山)-right->(基山):东三百里
    (基山)-right->(青丘山):东三百里
    (青丘山)-right->(箕尾山):东三百五十里

    (南次二山之首-柜山)-right->(长右山):东南四百五十里
    (长右山)-right->(尧光山):东三百四十里
    (尧光山)-right->(羽山):东三百五十里
    (羽山)-right->(瞿父山):东三百七十里
    (瞿父山)-right->(句余山):东四百里
    (句余山)-right->(浮玉山):东五百里
    (浮玉山)-right->(成山):东五百里
    (成山)-right->(会稽山):东五百里
    (会稽山)-right->(夷山):东五百里
    (夷山)-right->(仆勾山):东五百里
    (仆勾山)-right->(咸阴山):东五百里
    (咸阴山)-right->(洵山):东四百里
    (洵山)-right->(虖勺山):东四百里
    (虖勺山)-right->(区吴山):东五百里
    (区吴山)-right->(鹿吴山):东五百里
    (鹿吴山)-right->(漆吴山):东五百里

    (南次三山之首-天虞山)-right->(祷过山):东五百里
    (祷过山)-right->(发爽山):东五百里
    (发爽山)-right->(旄山):东四百里
    (旄山)-right->(非山):东四百里
    (非山)-right->(阳夹山):东五百里
    (阳夹山)-right->(灌湘山):东五百里
    (灌湘山)-right->(鸡山):东五百里
    (鸡山)-right->(令丘山):东四百里
    (令丘山)-right->(仑者山):东三百七十里
    (仑者山)-right->(禺槀山):东五百八十里
    (禺槀山)-right->(南禺山):东五百八十里

    (南山之首-鹊山-招摇山)-down->(南次二山之首-柜山)
    (南次二山之首-柜山)-down->(南次三山之首-天虞山)

}

rectangle 西山山系 {

    (西山之首-华山-钱来山)-left->(松果山):西四十五里
    (松果山)-left->(太华山):西六十里
    (太华山)-left->(小华山):西八十里
    (小华山)-left->(符禺山):西八十里
    (符禺山)-left->(石脆山):西六十里
    (石脆山)-left->(英山):西七十里
    (英山)-left->(竹山):西五十二里
    (竹山)-left->(浮山):西一百二十里
    (浮山)-left->(羭次山):西七十里
    (羭次山)-left->(时山):西一百五十里
    (时山)-left->(南山):西一百七十里
    (南山)-left->(大时山):西一百八十里
    (大时山)-left->(嶓冢山):西三百二十里
    (嶓冢山)-left->(天帝山):西三百五十里
    (天帝山)-left->(皋涂山):西南三百八十里
    (皋涂山)-left->(黄山):西一百八十里
    (黄山)-left->(翠山):西二百里
    (翠山)-left->(螝山):西二百五十里

    (西山第二列山系-首座山-铃山)-left->(泰冒山):西二百里
    (泰冒山)-left->(数历山):西一百七十里
    (数历山)-left->(高山):西一百五十里
    (高山)-left->(女床山):西南三百里
    (女床山)-left->(龙首山):西二百里
    (龙首山)-left->(鹿台山):西二百里
    (鹿台山)-left->(鸟危山):西二百里
    (鸟危山)-left->(小次山):西四百里
    (小次山)-left->(大次山):西三百里
    (大次山)-left->(薰吴山):西四百里
    (薰吴山)-left->(厎阳山):西四百里
    (厎阳山)-left->(众兽山):西二百五十里
    (众兽山)-left->(皇人山):西五百里
    (皇人山)-left->(中皇山):西三百里
    (中皇山)-left->(西皇山):西三百五十里
    (西皇山)-left->(莱山):西三百五十里

    (西山第三列山系-首座山-崇吾山)-left->(长沙山):西北三百里
    (长沙山)-left->(不周山):西北三百七十里
    (不周山)-left->(峚山):西北四百二十里
    (峚山)-left->(钟山):西北四百二十里
    (钟山)-left->(泰器山):西一百八十里
    (泰器山)-left->(槐江山):西三百二十里
    (槐江山)-left->(昆仑山):西四百里
    (昆仑山)-left->(乐游山):西三百七十里
    (乐游山)-left->(蠃母山):西水行四百里，流沙二百里
    (蠃母山)-left->(玉山):西三百五十里
    (玉山)-left->(轩辕丘):西四百八十里
    (轩辕丘)-left->(积石山):西三百里
    (积石山)-left->(长留山):西二百里
    (长留山)-left->(章莪山):西二百八十里
    (章莪山)-left->(阴山):西三百里
    (阴山)-left->(符惕山):西二百里
    (符惕山)-left->(三危山):西二百二十里
    (三危山)-left->(槐山):西一百九十里
    (槐山)-left->(天山):西三百五十里
    (天山)-left->(泑山):西二百九十里
    (泑山)-left->(翼望山):西水行百里

    (西山第四列山系-首座山-阴山)-up->(劳山):北五十里
    (劳山)-left->(罢谷山):西五十里
    (罢谷山)-up->(申山):北一百七十里
    (申山)-up->(鸟山):北二百里
    (鸟山)-up->(上申山):北一百二十里
    (上申山)-up->(诸次山):北一百八十里
    (诸次山)-up->(号山):北一百八十里
    (号山)-up->(盂山):北二百二十里
    (盂山)-left->(白於山):西二百五十里
    (白於山)-left->(申首山):西北三百里
    (申首山)-left->(泾谷山):西五十五里
    (泾谷山)-left->(刚山):西一百二十里
    (刚山)-left->(刚山的尾端):西二百里
    (刚山的尾端)-left->(英鞮山):西三百五十里
    (英鞮山)-left->(曲山):西三百里
    (曲山)-left->(邽山):西二百六十里
    (邽山)-left->(鸟鼠同穴山):西二百二十里
    (鸟鼠同穴山)-left->(崦嵫山):西南三百六十里

    (西山之首-华山-钱来山)-up->(西山第二列山系-首座山-铃山)
    (西山第二列山系-首座山-铃山)-up->(西山第三列山系-首座山-崇吾山)
    (西山第三列山系-首座山-崇吾山)-up->(西山第四列山系-首座山-阴山)

}

rectangle 北山山系 {

    (北山之首-单狐山)-up->(求如山):北二百五十里
    (求如山)-up->(带山):北三百里
    (带山)-up->(谯明山):北四百里
    (谯明山)-up->(涿光山):北三百五十里
    (涿光山)-up->(虢山):北三百八十里
    (虢山)-up->(虢山之尾):北四百里
    (虢山之尾)-up->(丹熏山):北二百里
    (丹熏山)-up->(石者山):北二百八十里
    (石者山)-up->(边春山):北百一十里
    (边春山)-up->(蔓联山):北二百里
    (蔓联山)-up->(单张山):北百八十里
    (单张山)-up->(灌题山):北三百二十里
    (灌题山)-up->(潘侯山):北二百里
    (潘侯山)-up->(小咸山):北二百三十里
    (小咸山)-up->(大咸山):北二百八十里
    (大咸山)-up->(敦薨山):北三百二十里
    (敦薨山)-up->(少咸山):北二百里
    (少咸山)-up->(狱法山):北二百里
    (狱法山)-up->(北岳山):北二百里
    (北岳山)-up->(浑夕山):北百八十里
    (浑夕山)-up->(北单山):北五十里
    (北单山)-up->(罴差山):北百里
    (罴差山)-up->(北鲜山):北百八十里
    (北鲜山)-up->(隄山):北百七十里

    (北次二山之首-管涔山)-up->(少阳山):北二百五十里
    (少阳山)-up->(县雍山):北五十里
    (县雍山)-up->(狐岐山):北二百里
    (狐岐山)-up->(白沙山):北三百五十里
    (白沙山)-up->(尔是山):北四百里
    (尔是山)-up->(狂山):北三百八十里
    (狂山)-up->(诸余山):北三百八十里
    (诸余山)-up->(敦头山):北三百五十里
    (敦头山)-up->(钩吾山):北三百五十里
    (钩吾山)-up->(北嚣山):北三百里
    (北嚣山)-up->(梁渠山):北三百五十里
    (梁渠山)-up->(姑灌山):北四百里
    (姑灌山)-up->(湖灌山):北三百八十里
    (湖灌山)-up->(洹山):北水行五百里，流沙三百里
    (洹山)-up->(敦题山):北三百里

    (北次三山之首-太行山-归山)-up->(龙侯山):东北二百里
    (龙侯山)-up->(马成山):东北二百里
    (马成山)-up->(咸山):东北七十里
    (咸山)-up->(天池山):东北二百里
    (天池山)-right->(阳山):东三百里
    (阳山)-right->(贲闻山):东三百五十里
    (贲闻山)-up->(王屋山):北百里
    (王屋山)-up->(教山):东北三百里
    (教山)-down->(景山):南三百里
    (景山)-down->(孟门山):东南三百二十里
    (孟门山)-down->(平山):东南三百二十里
    (平山)-right->(京山):东二百里
    (京山)-right->(虫尾山):东二百里
    (虫尾山)-right->(彭比山):东三百里
    (彭比山)-right->(小侯山):东百八十里
    (小侯山)-up->(泰头山):东三百七十里
    (泰头山)-up->(轩辕山):东北二百里
    (轩辕山)-up->(谒戾山):北二百里
    (谒戾山)-right->(沮洳山):东三百里
    (沮洳山)-up->(神囷山):北三百里
    (神囷山)-up->(发鸠山):北二百里
    (发鸠山)-up->(少山):东北百二十里
    (少山)-up->(锡山):东北二百里
    (锡山)-up->(景山):北二百里
    (景山)-up->(题首山):北百里
    (题首山)-up->(绣山):北百里
    (绣山)-up->(松山):北百二十里
    (松山)-up->(敦与山):北百二十里
    (敦与山)-up->(柘山):北百七十里
    (柘山)-up->(维龙山):北三百里
    (维龙山)-up->(白马山):北百八十里
    (白马山)-up->(空桑山):北二百里
    (空桑山)-up->(泰戏山):北三百里
    (泰戏山)-up->(石山):北三百里
    (石山)-up->(童戎山):北二百里
    (童戎山)-up->(高是山):北三百里
    (高是山)-up->(陆山):北三百里
    (陆山)-up->(沂山):北二百里
    (沂山)-up->(燕山):北百二十里
    (燕山)-up->(饶山):北山行五百里，水行五百里
    (饶山)-up->(乾山):北四百里
    (乾山)-up->(伦山):北五百里
    (伦山)-up->(碣石山):北五百里
    (碣石山)-up->(雁门山):北水行五百里
    (雁门山)-up->(帝都山):北水行四百里
    (帝都山)-up->(錞于毋逢山):北五百里

    (北山之首-单狐山)-right->(北次二山之首-管涔山)
    (北次二山之首-管涔山)-right->(北次三山之首-太行山-归山)

}

rectangle 东山山系 {
    
}

rectangle 中山山系 {
    
}

(中央)-down->南山山系:南
(中央)-left->西山山系:西
(中央)-up->北山山系:北
(中央)-right->东山山系:东
(中央)->中山山系:中





footer "2024/10/14, version 0.3"

@enduml